services:
  app:
    container_name: todolist
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_DNS=postgres://postgres:postgres@db:5432/todolist?sslmode=disable
      - MIGRATE_PATH=migrations
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d carrent" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s